プロパティの型定義からスキーマを生成する
EC-CUBE/eccube-api4 pull request #160
Opened 2023-09-20 07:13 UTC by chihiro-adachi

2023-09-20 08:58 UTC, kiy0taka requested changes

2023-09-20 08:58 UTC, kiy0taka commented on GraphQL/Types.php
> +                        'type' => $this->convertPhpTypeToType($prop->getType()),
`convertPhpTypeToType()`がnullを帰す場合があるので、その場合は`acc`に追加しないほうがいいかと思います。

2023-09-20 23:48 UTC, chihiro-adachi commented on GraphQL/Types.php
> +                        'type' => $this->convertPhpTypeToType($prop->getType()),
対応しました

2023-09-20 23:50 UTC, chihiro-adachi commented
更新対象のフィールドではないためnullableで定義するように変更しました
https://github.com/EC-CUBE/eccube-api4/pull/160/commits/34548ed62af784e1d810bec731f08839fe73d57a

2023-09-21 08:08 UTC, kiy0taka approved these changes

2023-09-21 08:09 UTC, merged