4.3対応
EC-CUBE/eccube-api4 pull request #164
Opened 2024-02-08 07:16 UTC by dotani1111

symfony6に対応しています。

2024-02-08 08:00 UTC, chihiro-adachi requested changes

2024-02-08 08:00 UTC, chihiro-adachi commented on composer.json
> +  "name": "ec-cube\/api42",
`\`は不要です。

2024-02-08 08:05 UTC, dotani1111 commented on composer.json
> +  "name": "ec-cube\/api42",
@chihiro-adachi 
修正致しました。

2024-02-21 08:20 UTC, ji-eunsoo commented
@dotani1111
インストールしたら、以下のエラーが発生しました。
一度ご確認のほど、よろしくお願いいたします。

◼︎環境:
- バージョン: 4.2.3
- PHPバージョン: 8.1
- データベース: PostgreSQL 14

◼︎エラー内容:
/Api42/EventListener/UserResolveListener.php (line 36)
```
Plugin\Api42\EventListener\UserResolveListener::__construct(): Argument #2 ($userPasswordEncoder) must be of type Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface, Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher given, called in /var/www/html/var/cache/dev/Container2iWGa8e/getUserResolveListenerService.php on line 24
```

2024-02-26 08:13 UTC, dotani1111 commented
@ji-eunsoo 
こちら対応致しました。
ご確認のほどよろしくお願い致します。

2024-02-27 06:20 UTC, ji-eunsoo commented
@dotani1111 
インストールすると、
```
Attempted to load class "LeagueOAuth2ServerBundle" from namespace "League\Bundle\OAuth2ServerBundle".
Did you forget a "use" statement for another namespace? 
```
というエラーになってしまいます。
一度ご確認のほど、よろしくお願いいたします。

2024-03-04 01:13 UTC, dotani1111 commented
@ji-eunsoo 
こちらはどのようにインストールしようとしましたか？
https://github.com/EC-CUBE/eccube-api4/pull/164#issuecomment-1965863861

2024-03-04 01:45 UTC, ji-eunsoo commented
@dotani1111 
インストールですが、独自プラグインで試しました。

2024-03-04 07:04 UTC, dotani1111 commented
@ji-eunsoo
環境情報を教えていただけますか？

2024-03-04 07:32 UTC, ji-eunsoo commented
@dotani1111
◼︎環境:
バージョン: 4.2.3
PHPバージョン: 8.1
データベース: PostgreSQL 14
となります。

2024-03-05 05:02 UTC, ji-eunsoo commented
`Fatal error: Uncaught Error: Class "League\Bundle\OAuth2ServerBundle\LeagueOAuth2ServerBundle" not found in /Users/eunsoo_ji/eccube/ec-cube/src/Eccube/Kernel.php:108 Stack trace: #0 /Users/eunsoo_ji/eccube/ec-cube/vendor/symfony/http-kernel/Kernel.php(346): Eccube\Kernel->registerBundles() #1 /Users/eunsoo_ji/eccube/ec-cube/vendor/symfony/http-kernel/Kernel.php(762): Symfony\Component\HttpKernel\Kernel->initializeBundles() #2 /Users/eunsoo_ji/eccube/ec-cube/vendor/symfony/http-kernel/Kernel.php(185): Symfony\Component\HttpKernel\Kernel->preBoot() #3 /Users/eunsoo_ji/eccube/ec-cube/index.php(83): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /Users/eunsoo_ji/eccube/ec-cube/src/Eccube/Kernel.php on line 108`

2024-04-08 23:53 UTC, chihiro-adachi commented
依存関係があるため、独自プラグインではインストールできません。
https://github.com/EC-CUBE/ec-cube/issues/4257

composer経由でのインストールでは事象は発生しないため、マージします。

2024-04-08 23:53 UTC, merged